name: Backup Restore Functional E2E Tests Trigger

run-name: >
  Rancher=${{ inputs.rancher_version }}, RKE2 Version=${{ inputs.upstream_cluster_version }}, destroy=${{ inputs.destroy_runner }}

on:
  workflow_dispatch:
    inputs:
      rancher_version:
        description: Rancher Manager version
        type: string
        required: true
      upstream_cluster_version:
        description: Rancher (RKE2) version
        default: v1.32.5+rke2r1
        type: string
        required: true
      destroy_runner:
        description: Destroy runner
        default: true
        type: boolean
      rancher_repo:
        description: Rancher Manager repository
        default: https://releases.rancher.com/server-charts/latest
        type: string
        required: true

      # Add a Qase run ID input (can be 'auto', 'none', or a numeric run ID)
      qase_run_id:
        description: Qase run ID for reporting (e.g., 'auto', 'none', or an ID like '123')
        default: 'none'
        type: string
        required: false


jobs:
  e2e:
    uses: ./.github/workflows/backup-restore-e2e.yaml
    with:
      destroy_runner: ${{ inputs.destroy_runner }}
      rancher_version: ${{ inputs.rancher_version }}
      upstream_cluster_version: ${{ inputs.upstream_cluster_version }}
      rancher_repo: ${{ inputs.rancher_repo }}
      qase_run_id: ${{ inputs.qase_run_id }}
    secrets:
      aws_access_key: ${{ secrets.BR_AWS_ACCESS_KEY_ID }}
      aws_secret_key: ${{ secrets.BR_AWS_SECRET_ACCESS_KEY }}
      rancher_password: ${{ secrets.BR_RANCHER_PASSWORD }}
      instance_ssh_key: ${{ secrets.BR_INSTANCE_SSH_KEY }}
      aws_region: ${{ secrets.BR_AWS_REGION }}
      key_name: ${{ secrets.BR_AWS_KEY_NAME }}
      encryption_secret_key: ${{ secrets.BR_ENCRYPTION_SECRET_KEY }}
      qase_api_token: ${{ secrets.BR_QASE_API_TOKEN }}
